/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tcpMessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tcpMessage.pb-c.h"
void   tcp__message__relay_config__init
                     (TCPMESSAGE__RelayConfig         *message)
{
  static const TCPMESSAGE__RelayConfig init_value = TCP__MESSAGE__RELAY_CONFIG__INIT;
  *message = init_value;
}
size_t tcp__message__relay_config__get_packed_size
                     (const TCPMESSAGE__RelayConfig *message)
{
  assert(message->base.descriptor == &tcp__message__relay_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcp__message__relay_config__pack
                     (const TCPMESSAGE__RelayConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcp__message__relay_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcp__message__relay_config__pack_to_buffer
                     (const TCPMESSAGE__RelayConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcp__message__relay_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TCPMESSAGE__RelayConfig *
       tcp__message__relay_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TCPMESSAGE__RelayConfig *)
     protobuf_c_message_unpack (&tcp__message__relay_config__descriptor,
                                allocator, len, data);
}
void   tcp__message__relay_config__free_unpacked
                     (TCPMESSAGE__RelayConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tcp__message__relay_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tcp__message__message__init
                     (TCPMESSAGE__Message         *message)
{
  static const TCPMESSAGE__Message init_value = TCP__MESSAGE__MESSAGE__INIT;
  *message = init_value;
}
size_t tcp__message__message__get_packed_size
                     (const TCPMESSAGE__Message *message)
{
  assert(message->base.descriptor == &tcp__message__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcp__message__message__pack
                     (const TCPMESSAGE__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcp__message__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcp__message__message__pack_to_buffer
                     (const TCPMESSAGE__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcp__message__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TCPMESSAGE__Message *
       tcp__message__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TCPMESSAGE__Message *)
     protobuf_c_message_unpack (&tcp__message__message__descriptor,
                                allocator, len, data);
}
void   tcp__message__message__free_unpacked
                     (TCPMESSAGE__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tcp__message__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tcp__message__relay_config__field_descriptors[2] =
{
  {
    "relayId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__RelayConfig, relayid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relayStatus",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__RelayConfig, relaystatus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcp__message__relay_config__field_indices_by_name[] = {
  0,   /* field[0] = relayId */
  1,   /* field[1] = relayStatus */
};
static const ProtobufCIntRange tcp__message__relay_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tcp__message__relay_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TCP_MESSAGE.RelayConfig",
  "RelayConfig",
  "TCPMESSAGE__RelayConfig",
  "TCP_MESSAGE",
  sizeof(TCPMESSAGE__RelayConfig),
  2,
  tcp__message__relay_config__field_descriptors,
  tcp__message__relay_config__field_indices_by_name,
  1,  tcp__message__relay_config__number_ranges,
  (ProtobufCMessageInit) tcp__message__relay_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tcp__message__message__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Message, type),
    &tcp__message__payload_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aliveResponse",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Message, aliveresponse),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relayConfig",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TCPMESSAGE__Message, n_relayconfig),
    offsetof(TCPMESSAGE__Message, relayconfig),
    &tcp__message__relay_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sec1",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Message, sec1),
    &sec1_payload__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcp__message__message__field_indices_by_name[] = {
  1,   /* field[1] = aliveResponse */
  2,   /* field[2] = relayConfig */
  3,   /* field[3] = sec1 */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tcp__message__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tcp__message__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TCP_MESSAGE.Message",
  "Message",
  "TCPMESSAGE__Message",
  "TCP_MESSAGE",
  sizeof(TCPMESSAGE__Message),
  4,
  tcp__message__message__field_descriptors,
  tcp__message__message__field_indices_by_name,
  1,  tcp__message__message__number_ranges,
  (ProtobufCMessageInit) tcp__message__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue tcp__message__payload_type__enum_values_by_number[8] =
{
  { "Alive_Request", "TCP__MESSAGE__PAYLOAD_TYPE__Alive_Request", 0 },
  { "Alive_Response", "TCP__MESSAGE__PAYLOAD_TYPE__Alive_Response", 1 },
  { "Relay_Command_Request", "TCP__MESSAGE__PAYLOAD_TYPE__Relay_Command_Request", 2 },
  { "Relay_Command_Response", "TCP__MESSAGE__PAYLOAD_TYPE__Relay_Command_Response", 3 },
  { "Relay_Status_Request", "TCP__MESSAGE__PAYLOAD_TYPE__Relay_Status_Request", 4 },
  { "Relay_Status_Response", "TCP__MESSAGE__PAYLOAD_TYPE__Relay_Status_Response", 5 },
  { "Security_Session_Request", "TCP__MESSAGE__PAYLOAD_TYPE__Security_Session_Request", 6 },
  { "Security_Session_Response", "TCP__MESSAGE__PAYLOAD_TYPE__Security_Session_Response", 7 },
};
static const ProtobufCIntRange tcp__message__payload_type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex tcp__message__payload_type__enum_values_by_name[8] =
{
  { "Alive_Request", 0 },
  { "Alive_Response", 1 },
  { "Relay_Command_Request", 2 },
  { "Relay_Command_Response", 3 },
  { "Relay_Status_Request", 4 },
  { "Relay_Status_Response", 5 },
  { "Security_Session_Request", 6 },
  { "Security_Session_Response", 7 },
};
const ProtobufCEnumDescriptor tcp__message__payload_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TCP_MESSAGE.PayloadType",
  "PayloadType",
  "TCPMESSAGE__PayloadType",
  "TCP_MESSAGE",
  8,
  tcp__message__payload_type__enum_values_by_number,
  8,
  tcp__message__payload_type__enum_values_by_name,
  1,
  tcp__message__payload_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
