/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TCPRequest.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TCPRequest.pb-c.h"
void   tcp__message__payload__init
                     (TCPMESSAGE__Payload         *message)
{
  static const TCPMESSAGE__Payload init_value = TCP__MESSAGE__PAYLOAD__INIT;
  *message = init_value;
}
size_t tcp__message__payload__get_packed_size
                     (const TCPMESSAGE__Payload *message)
{
  assert(message->base.descriptor == &tcp__message__payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tcp__message__payload__pack
                     (const TCPMESSAGE__Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tcp__message__payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tcp__message__payload__pack_to_buffer
                     (const TCPMESSAGE__Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tcp__message__payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TCPMESSAGE__Payload *
       tcp__message__payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TCPMESSAGE__Payload *)
     protobuf_c_message_unpack (&tcp__message__payload__descriptor,
                                allocator, len, data);
}
void   tcp__message__payload__free_unpacked
                     (TCPMESSAGE__Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tcp__message__payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tcp__message__payload__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Payload, type),
    &tcp__message__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sec1",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Payload, sec1),
    &sec1_payload__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relayNumber",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Payload, relaynumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relayState",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Payload, relaystate),
    &tcp__message__relay_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "StringData",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TCPMESSAGE__Payload, stringdata),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tcp__message__payload__field_indices_by_name[] = {
  4,   /* field[4] = StringData */
  2,   /* field[2] = relayNumber */
  3,   /* field[3] = relayState */
  1,   /* field[1] = sec1 */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tcp__message__payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor tcp__message__payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TCP_MESSAGE.Payload",
  "Payload",
  "TCPMESSAGE__Payload",
  "TCP_MESSAGE",
  sizeof(TCPMESSAGE__Payload),
  5,
  tcp__message__payload__field_descriptors,
  tcp__message__payload__field_indices_by_name,
  1,  tcp__message__payload__number_ranges,
  (ProtobufCMessageInit) tcp__message__payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue tcp__message__relay_state__enum_values_by_number[2] =
{
  { "TurnOff", "TCP__MESSAGE__RELAY_STATE__TurnOff", 0 },
  { "TurnOn", "TCP__MESSAGE__RELAY_STATE__TurnOn", 1 },
};
static const ProtobufCIntRange tcp__message__relay_state__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex tcp__message__relay_state__enum_values_by_name[2] =
{
  { "TurnOff", 0 },
  { "TurnOn", 1 },
};
const ProtobufCEnumDescriptor tcp__message__relay_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TCP_MESSAGE.RelayState",
  "RelayState",
  "TCPMESSAGE__RelayState",
  "TCP_MESSAGE",
  2,
  tcp__message__relay_state__enum_values_by_number,
  2,
  tcp__message__relay_state__enum_values_by_name,
  1,
  tcp__message__relay_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue tcp__message__message_type__enum_values_by_number[3] =
{
  { "NewSecuritySession", "TCP__MESSAGE__MESSAGE_TYPE__NewSecuritySession", 0 },
  { "SwitchRelayRequest", "TCP__MESSAGE__MESSAGE_TYPE__SwitchRelayRequest", 1 },
  { "PayloadData", "TCP__MESSAGE__MESSAGE_TYPE__PayloadData", 2 },
};
static const ProtobufCIntRange tcp__message__message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex tcp__message__message_type__enum_values_by_name[3] =
{
  { "NewSecuritySession", 0 },
  { "PayloadData", 2 },
  { "SwitchRelayRequest", 1 },
};
const ProtobufCEnumDescriptor tcp__message__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TCP_MESSAGE.MessageType",
  "MessageType",
  "TCPMESSAGE__MessageType",
  "TCP_MESSAGE",
  3,
  tcp__message__message_type__enum_values_by_number,
  3,
  tcp__message__message_type__enum_values_by_name,
  1,
  tcp__message__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
