/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TCPRequest.proto */

#ifndef PROTOBUF_C_TCPRequest_2eproto__INCLUDED
#define PROTOBUF_C_TCPRequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "sec1.pb-c.h"

typedef struct _TCPMESSAGE__Payload TCPMESSAGE__Payload;


/* --- enums --- */

typedef enum _TCPMESSAGE__RelayState {
  TCP__MESSAGE__RELAY_STATE__TurnOff = 0,
  TCP__MESSAGE__RELAY_STATE__TurnOn = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TCP__MESSAGE__RELAY_STATE)
} TCPMESSAGE__RelayState;
typedef enum _TCPMESSAGE__MessageType {
  TCP__MESSAGE__MESSAGE_TYPE__NewSecuritySession = 0,
  TCP__MESSAGE__MESSAGE_TYPE__SwitchRelayRequest = 1,
  TCP__MESSAGE__MESSAGE_TYPE__PayloadData = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TCP__MESSAGE__MESSAGE_TYPE)
} TCPMESSAGE__MessageType;

/* --- messages --- */

struct  _TCPMESSAGE__Payload
{
  ProtobufCMessage base;
  TCPMESSAGE__MessageType type;
  Sec1Payload *sec1;
  uint32_t relaynumber;
  TCPMESSAGE__RelayState relaystate;
  char *stringdata;
};
#define TCP__MESSAGE__PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tcp__message__payload__descriptor) \
    , TCP__MESSAGE__MESSAGE_TYPE__NewSecuritySession, NULL, 0, TCP__MESSAGE__RELAY_STATE__TurnOff, (char *)protobuf_c_empty_string }


/* TCPMESSAGE__Payload methods */
void   tcp__message__payload__init
                     (TCPMESSAGE__Payload         *message);
size_t tcp__message__payload__get_packed_size
                     (const TCPMESSAGE__Payload   *message);
size_t tcp__message__payload__pack
                     (const TCPMESSAGE__Payload   *message,
                      uint8_t             *out);
size_t tcp__message__payload__pack_to_buffer
                     (const TCPMESSAGE__Payload   *message,
                      ProtobufCBuffer     *buffer);
TCPMESSAGE__Payload *
       tcp__message__payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tcp__message__payload__free_unpacked
                     (TCPMESSAGE__Payload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TCPMESSAGE__Payload_Closure)
                 (const TCPMESSAGE__Payload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    tcp__message__relay_state__descriptor;
extern const ProtobufCEnumDescriptor    tcp__message__message_type__descriptor;
extern const ProtobufCMessageDescriptor tcp__message__payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_TCPRequest_2eproto__INCLUDED */
